### ISSUE TITLE
Issue w/ mariadb

### ISSUE THREAD

**Issue by Chaprnks** [electronfriends/wemp#10]
Starting with version 0.9.2, mariadb download fails.

Error log:
![fzhp3VO](https://github.com/electronfriends/wemp/assets/6340970/fb6dad44-c171-4bcb-9a67-6ff50e9002f3)

**Comment by electronfriends** [comment]
Can you try another DNS resolver? For example, [Cloudflare DNS](https://1.1.1.1/dns/)

The download from https://archive.mariadb.org/mariadb-11.3.2/winx64-packages/mariadb-11.3.2-winx64.zip should work.
