### ISSUE TITLE
Timeout Issues with Single php-cgi Process Handling Multiple Requests

### ISSUE THREAD

**Issue by danielchristianschroeter** [electronfriends/wemp#11]
### Issue Description
When executing multiple concurrent requests, I am encountering timeout issues. It appears that only one `php-cgi` process is spawned to handle all the requests, which leads to requests being queued and eventually timing out, especially if they are complex or resource-intensive.

### Expected Behavior
Ideally, multiple `php-cgi` processes should be spawned automatically to handle multiple concurrent requests efficiently, preventing timeouts and ensuring better performance.

### Steps to Reproduce
1. Set up WEMP with the default configuration.
2. Execute multiple concurrent requests that require processing by `php-cgi`. (e.g. curl_setopt)
3. Observe that only one `php-cgi` process is handling all the requests, leading to timeouts.

### Environment
- WEMP version: 0.9.8
- NGINX version: 1.26.0
- PHP version: 8.3.7
- Windows version: 11

### Additional Context
This issue does not occur when using Apache, where multiple requests are handled without timeouts. The problem seems specific to how WEMP is managing `php-cgi` processes under load.

I would appreciate any guidance on how to configure WEMP to spawn multiple `php-cgi` processes or any other recommended solutions to this problem. I think PHP-FPM (FastCGI Process Manager) is designed to spawn and manage multiple PHP processes. 

Thank you for your assistance! Very great project and a good alternative to XAMPP.

**Comment by danielchristianschroeter** [comment]
Here some simple solution or workaround:
1. Open C:\wemp\php and create `start-php-cgi.bat` with the following content:

```
@echo off
SET PHP_CGI=php-cgi.exe
SET PHP_INI=php.ini

ECHO Starting multiple PHP-CGI processes...

START /B "" "%PHP_CGI%" -b 127.0.0.1:9001 -c "%PHP_INI%"
START /B "" "%PHP_CGI%" -b 127.0.0.1:9002 -c "%PHP_INI%"
START /B "" "%PHP_CGI%" -b 127.0.0.1:9003 -c "%PHP_INI%"
START /B "" "%PHP_CGI%" -b 127.0.0.1:9004 -c "%PHP_INI%"

ECHO All PHP-CGI processes started.
```

2. Add a upstream in your C:\wemp\nginx\conf\nginx.conf (within `http` block)
```
	upstream php_cgi_pool {
		server 127.0.0.1:9000;
		server 127.0.0.1:9001;
		server 127.0.0.1:9002;
		server 127.0.0.1:9003;
		server 127.0.0.1:9004;
	}
```

3. Replace `fastcgi_pass   127.0.0.1:9000;` with `fastcgi_pass php_cgi_pool;` in your C:\wemp\nginx\conf\nginx.conf

**Comment by danielchristianschroeter** [comment]
Here is a PowerShell script that monitors php-cgi processes on specified ports and restarts them if terminated.

`spawn-cgi-php.ps1`
```
# Define the ports and the PHP CGI executable
$ports = @(9001, 9002, 9003, 9004)
$phpCgi = "php-cgi.exe"
$phpIni = "php.ini"

# Get the directory of the current script
$scriptPath = Split-Path -Parent -Path $MyInvocation.MyCommand.Definition

# Function to check if a PHP-CGI process is running on a specific port
function Is-ProcessRunning {
    param($port)
    $processName = "$phpCgi -b 127.0.0.1:$port"
    $runningProcesses = Get-WmiObject Win32_Process -Filter "name = '$phpCgi'" | Select-Object CommandLine
    foreach ($process in $runningProcesses) {
        if ($process.CommandLine -match "127\.0\.0\.1:$port") {
            return $true
        }
    }
    return $false
}

# Function to start a PHP-CGI process
function Start-PhpCgiProcess {
    param($port)
    Start-Process -NoNewWindow -FilePath $phpCgi -ArgumentList "-b 127.0.0.1:$port -c $phpIni" -WorkingDirectory $scriptPath
    Write-Host "Started PHP-CGI on port $port"
}

# Display the initial message
Write-Host "Monitoring PHP-CGI processes. Press Ctrl+C to exit."

# Main loop to monitor and restart the processes
while ($true) {
    foreach ($port in $ports) {
        if (-not (Is-ProcessRunning -port $port)) {
            Start-PhpCgiProcess -port $port
        }
    }
    Start-Sleep -Seconds 5
}
```

**Comment by electronfriends** [comment]
I will close this issue as I do not plan to implement my own FastCGI process manager. Another workaround might be to set `PHP_FCGI_MAX_REQUESTS` as a system variable to 0 or something higher than 500.

However, until FPM is available for Windows, nothing in Wemp will change in this regard.
