### ISSUE TITLE
Add progress bar when downloading services

### ISSUE THREAD

**Issue by 2dragonly** [electronfriends/wemp#12]
Why there's only popup notification, add something progress bar on menu, or show the services, then just hide the options when that service still not available, then shows the progress bar inside of the option menu.. so, that we can tell it is still downloading..

And also, why the notification have `close` button? do you expect the user to cancel downloading the service? when it's required for the app to function?

**Comment by electronfriends** [comment]
Wemp uses the Windows notifications and they always have a close button. They also do not support progress bars and will not cancel the download when closed.
